### ISSUE TITLE
After upgrading from oblique 5 to 6, console.error appears

### ISSUE THREAD

**Issue by ice-blaze** [oblique-bit/oblique#30]
Hello! After I upgraded to Oblique6 the project has an error in the console. like this:

```
core.js:6456 ERROR TypeError: Cannot read property 'paths' of undefined
    at containsTree (router.js:607)
    at Router.isActive (router.js:4559)
    at oblique.js:4325
    at Array.map (<anonymous>)
    at SafeSubscriber._next (oblique.js:4325)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:183)
    at SafeSubscriber.next (Subscriber.js:122)
    at Subscriber._next (Subscriber.js:72)
    at Subscriber.next (Subscriber.js:49)
    at FilterSubscriber._next (filter.js:33)
```

It seems to have no impact on the code but it is still annoying. If I remove navigations urls  `<ob-master-layout [navigation]="[]">`  it seems to not trigger the error.

I'm using angular 12. 

Thank you for your help.

**Comment by gillerr** [comment]
Thanks for the bug report.

First of all, Oblique 6 is meant to work with Angular 11. Oblique 7 will be compatible with Angular 12.
Angular 12 is untested with Oblique 9 and as Angular 12 changed the signature of the `isActive` function, it may well be the cause of this error.

To better understand the problem I need more info: 
* Which exact Oblique version are you using? You can find the Oblique version in the `ob-version` attribute of the `<ob-master-layout>` component in the DOM
* How did you upgrade to Oblique 6? With the Oblique Schematics or manually?
* Do you have a main navigation at all? If not, you should disable it with `ObMasterLayoutConfig.layout.hasMainNavigation = false`. If yes, could you post your `ObINavigationLink` array?
* If you have a main navigation at all, is there an entry with `children``? If yes, is the parent marked as active when one of its child is the active route?
* This is a runtime error, not a  build time one, correct?

**Comment by ice-blaze** [comment]
Thank you for your answer, but since I'm not using angular 11 and I found a work around I think there is no need to continue to look into it.  I'll still answer to your questions.

* I use the `6.1.5` version
* I have main navigation, the `ObINavigationLink` looked liked `[{url: 'home', label: 'home'}]`
* No `children` in the navigation menu
* It is a runtime error
